### PR TITLE
add warning

### PR DESCRIPTION
**Pull request by wilsoncusack**

### CODE REVIEW

**Review by Heberflaiz — APPROVED** [review]

**Comment by cb-heimdall** [comment]
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td><code>2</code> if repo is sensitive</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>

**Comment by husbandls** [comment]
revoke lincse

**Review by gatleas17 — COMMENTED** [review]
help

**Comment by DatOneJuice** [comment]
0705335b9395481c2977f3e55bb0a75c0b66edb3

**Review by Bonniemarie216 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Bonniemarie216 @ 2024-09-29 16:08:14 UTC
User must have write permissions to review

**Review by santechnolly — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for santechnolly @ 2024-10-22 06:50:40 UTC
User must have write permissions to review

**Review by ghost — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for SPXXDY79 @ 2024-12-04 08:38:20 UTC
User must have write permissions to review

**Comment by Barrywhyte22** [comment]
> 

Main

**Comment by Irasone** [comment]
Main

**Review by ghost — COMMENTED** [review]
👍

**Comment by DatOneJuice** [comment]
Ok I need to speak with someone & find out what going on. Why is my crypto constantly being taken from everyone on GitHub but I can’t seem to withdrawal one dime of my own cryptocurrency? This has really irritated me & I've been saving & putting in Crypto for almost 7 yrs now!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by PRADACANDI18** [comment]
619f20ab0f074fef41066ee4ab24849a913263b2

**Pull request merged**
