### PR TITLE
🔧 chore: add remappings

### PR DESCRIPTION
**Pull request by cruzdanilo**
improves integration with solidity development tools.

example: fixes vscode solidity integration.

### CODE REVIEW

**Comment by wilsoncusack** [comment]
Appreciate! Can you say more if the issues you're facing. We like to avoid specifying remappings, re 2(c)(1) https://github.com/coinbase/solidity-style-guide

**Comment by cruzdanilo** [comment]
hey @wilsoncusack! when using `webauthn-sol` as a library, vscode solidity extension won't resolve the imports. here is a screenshot and a very simple repro: https://github.com/cruzdanilo/repro-webauthn

Screenshot 2024-04-04 at 18 15 13

**Comment by wilsoncusack** [comment]
I wonder if it depends on the solidity extension you use. These work for me.

**Comment by cruzdanilo** [comment]
i am using this one: https://github.com/juanfranblanco/vscode-solidity
i think it's the most used one and should work out of the box.
which one are you using?

**Comment by wilsoncusack** [comment]
https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity

**Comment by wilsoncusack** [comment]
Thanks for opening the issue, going to close for now!

**Pull request closed without merging**
